a = input ("Digite algo: ")
print ("O tipo primitivo desse valor é ", type (a))
print ("Só tem espaços? ", a.isspace ())
print ("É um número? ", a.isnumeric ())
print ("É alfabetico? ", a.isalpha ())
print ("É alfanúmerico? ", a.isalnum ())
print ("Ésta em letras maiúsculas?", a.isupper ())
print ("Esta em letras minúsculas?", a.islower ())
print ("Esta capitalizada? ", a.istitle ())